# Generated by Django 4.2.1 on 2023-06-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('social', 'Social'), ('school', 'School'), ('gaming', 'Gaming')], max_length=20)),
            ],
        ),
    ]
